openapi: 3.0.3
info:
  title: Bookify's Suscription - OpenAPI 3.0
  description: This is the API implementation for Bookify' suscription operations
  version: 1.0.0
servers:
- url: /
tags:
- name: suscription
  description: Actions with Bookify's suscriptions
paths:
  /suscription:
    get:
      tags:
      - suscription
      summary: Get all active suscriptions info
      description: Returns all active suscriptions data
      operationId: getNSubs
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Suscription'
                x-content-type: application/json
            application/xml:
              schema:
                $ref: '#/components/schemas/Suscription'
        "400":
          description: Invalid ID supplied
        "404":
          description: Suscription not found
      x-swagger-router-controller: Suscription
    post:
      tags:
      - suscription
      summary: New suscription
      description: Creates a new suscription for a Bookify's user
      operationId: newSub
      requestBody:
        description: userId to suscribe
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Suscription'
            application/xml:
              schema:
                $ref: '#/components/schemas/Suscription'
      x-swagger-router-controller: Suscription
  /suscription/{userId}:
    get:
      tags:
      - suscription
      summary: Get user suscription info
      description: Returns the active suscription data
      operationId: getSuscription
      parameters:
      - name: userId
        in: path
        description: ID of the user that need to see his suscription info
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Suscription'
            application/xml:
              schema:
                $ref: '#/components/schemas/Suscription'
        "400":
          description: Invalid ID supplied
        "404":
          description: Suscription not found
      x-swagger-router-controller: Suscription
    put:
      tags:
      - suscription
      summary: Update suscription data
      description: This can only be done by the logged in user.
      operationId: updateSuscription
      parameters:
      - name: userId
        in: path
        description: ID of the user that need his suscription to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        description: Update an existent user suscription
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Suscription'
          application/xml:
            schema:
              $ref: '#/components/schemas/Suscription'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Suscription'
      responses:
        default:
          description: successful operation
      x-swagger-router-controller: Suscription
    delete:
      tags:
      - suscription
      summary: Delete active suscription
      description: This can only be done by the logged in user.
      operationId: deleteSuscription
      parameters:
      - name: userId
        in: path
        description: ID of the user that need his suscription to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "400":
          description: Invalid user ID supplied
        "404":
          description: Suscription not found
      x-swagger-router-controller: Suscription
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
      example:
        id: 1
      xml:
        name: user
    Suscription:
      type: object
      properties:
        userId:
          type: integer
          example: 1
        startDate:
          type: string
          example: 16/11/2022
        endDate:
          type: string
          example: 16/12/2022
        price:
          type: number
          example: 5.49
      example:
        endDate: 16/12/2022
        price: 5.49
        userId: 1
        startDate: 16/11/2022
      xml:
        name: subcription

